# Generated by Django 4.2.1 on 2023-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_this',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('filee', models.FileField(upload_to='')),
            ],
        ),
    ]
