# Generated by Django 4.2.1 on 2023-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_this',
            name='subject',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='email_this',
            name='filee',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='email_this',
            name='message',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AlterField(
            model_name='email_this',
            name='to',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
