# Generated by Django 4.2.1 on 2023-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_Email', '0002_email_this_subject_alter_email_this_filee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_this',
            name='to',
            field=models.CharField(default='not_null', max_length=255),
        ),
    ]
